# Generated by Django 5.1 on 2024-08-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('soustheme', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=3000)),
                ('modalites', models.TextField(max_length=500)),
                ('logo', models.FileField(upload_to='images')),
                ('nombre_de_participant', models.IntegerField(default=0)),
                ('duree', models.CharField(max_length=30)),
            ],
        ),
    ]
