# Generated by Django 5.1 on 2024-09-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icares_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=200)),
                ('ecole', models.CharField(max_length=200)),
                ('isParticipant', models.BooleanField()),
                ('epreuve', models.JSONField()),
                ('formule', models.IntegerField()),
            ],
        ),
    ]
