# Generated by Django 5.1 on 2024-09-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icares_site', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='epreuve',
        ),
        migrations.AddField(
            model_name='user',
            name='epreuve',
            field=models.ManyToManyField(to='icares_site.epreuve'),
        ),
    ]
