# Generated by Django 5.1 on 2024-10-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icares_site', '0007_alter_user_isparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lille', models.CharField(max_length=300)),
                ('lyon', models.CharField(max_length=300)),
                ('paris', models.CharField(max_length=300)),
                ('marseille', models.CharField(max_length=300)),
                ('nantes', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='formule',
            field=models.IntegerField(blank=True, choices=[(1, 'Entrée'), (2, 'Entrée + Repas'), (3, 'Entrée + Repas + Logement')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='isParticipant',
            field=models.IntegerField(choices=[(0, 'Participant'), (1, 'Spectateur'), (2, 'Jury')], default=0, verbose_name='Etat'),
        ),
    ]
