# Generated by Django 5.1 on 2024-10-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icares_site', '0009_alter_lien_lille_alter_lien_lyon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='epreuve_jury',
            field=models.ManyToManyField(blank=True, related_name='jury_members', to='icares_site.epreuve'),
        ),
        migrations.AddField(
            model_name='user',
            name='isJury',
            field=models.BooleanField(default=False, verbose_name='Jury'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='modalites',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='epreuve',
            field=models.ManyToManyField(related_name='participants', to='icares_site.epreuve'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isParticipant',
            field=models.IntegerField(choices=[(0, 'Participant'), (1, 'Spectateur')], default=0, verbose_name='Etat'),
        ),
    ]
